### ISSUE TITLE
Add ability to change primary email address

### ISSUE THREAD

**Issue by MagicFab** [pentacent/keila#191]
I'd like to change the primary email for my account at Keila.io. I can't seem to find how if it's possible.

This should probably be under "Account"

**Comment by wmnnd** [comment]
Hey, thanks for reaching out! It’s currently not possible and because it’s actually quite difficult to get this right from a security perspective, this feature is not in the immediate roadmap. In the medium term, I agree, this is a feature that should be added.

I’ll get in touch with you regarding your account on keila.io and close this ticket for now. :smiley:
