### ISSUE TITLE
Improvement suggestions for setup guide

### ISSUE THREAD

**Issue by pascalwengerter** [pentacent/keila#24]
Two things I've come across when trying to get the `pentacent/keila` Docker image running today:

1. I needed to create a SECRET_KEY_BASE environment variable myself. It would be nice if it was mentioned in the setup guide, since it's quite easily done with:

```sh
mix phx.gen.secret
```

2. I am not sure if the DATABASE_URL environment variable needs the `@HOST` config parameter. In the docs you mention _URL following the schema **postgres://user:password/database**_, while the official documentation suggests something along the lines of _DATABASE_URL="**ecto://USERNAME:PASSWORD@localhost/database**"_.

**Comment by wmnnd** [comment]
1. Correct. I didn’t include this in the setup guide because you’d have to have Phoenix installed in prod which is unlikely when running from a Docker image. So maybe something like this might be more useful: `head -c 32 /dev/urandom | base64`

2. Very correct! This is a mistake in the docs.

**Comment by pascalwengerter** [comment]
>     1. Correct. I didn’t include this in the setup guide because you’d have to have Phoenix installed in prod which is unlikely when running from a Docker image. So maybe something like this might be more useful: `head -c 32 /dev/urandom | base64`
> 
>     2. Very correct! This is a mistake in the docs.

1. Nice, yeah! I ended up installing Phoenix locally to test some things and could copy-paste the result, but yours is even better :)

2. Now I feel less bad for ultimatively failing at getting things running, haha! Could you provide more context in the docs how to handle the database connection? (I was a bit confused on where Phoenix would look for `localhost` given that it runs in a container and postgres outside of it, after all)

**Comment by wmnnd** [comment]
re 2) So the URL definitely needs to include a host. In my prod setup, both Keila and Postgres are in containers, in a shared network, so the URL looks something like this: `postgres://user:password@postgres/db`. (The schema is actually ignored by Ecto, it can be `postgres://`, `ecto://`, or `whatever://`).
On my dev machine I have Postgres running in a container and Keila locally, so since the Postgres container exposes its port to localhost, the URl is `postgres://user:password@localhost/db`.
I haven’t tested the option where Postgres is running locally and Keila in a container. I assume that you might have to create a bridge network for something like that.

**Comment by wmnnd** [comment]
I’ve added the new guidance both as a hint when running Keila (via 475b63a863858ad022ac681549b9d82b80c90282) and to the docs (via https://github.com/pentacent/keila-web/commit/d4ed230176bc26a8d33fd455a54fffa7f30cb97d). Thanks for bringing this up!
