### ISSUE TITLE
No menu in the campaign editor (iPad)

### ISSUE THREAD

**Issue by Blotmonath** [pentacent/keila#250]
On my iPad Pro, there is no menu in the campaign editor to create a new newsletter via Safari and Firefox. Only h1, h2 and h3 are displayed.

You just can't see the menu icons...you can still select them.

If you use Safari or Firefox on the MacBook, everything is normally usable and visible.

Does this error also occur with others?
![IMG_0377](https://github.com/pentacent/keila/assets/151517703/366ac8fe-99d6-48bd-86e0-201d37020806)
![IMG_0380](https://github.com/pentacent/keila/assets/151517703/d56dca32-2e05-4e28-94df-40c4584f9ef8)

**Comment by wmnnd** [comment]
Hey there, thanks for reporting! I’ll close the issue for now because I don’t have an iPad to test it myself, so I can’t really investigate this any further. If you have more information on what might be causing the issue, feel free to reopen :slightly_smiling_face: 

One suspicion I have is that you might be using an old version of Safari, maybe you can look into whether it works correctly on a newer version of Safari or a newer iPad.
