### ISSUE TITLE
Shared SMTP senders?

### ISSUE THREAD

**Issue by flinthamm** [pentacent/keila#261]
First of all a massive thank you to pentacent for this amazing project.

Forgive me if this is a stupid question but for smaller projects that only require SMTP, is there any reason why a shared SMTP sender to be shared across all projects cannot be setup? Do I have to enable an environment flag or similar in order to enable this, because most if not all emails will only ever need to be sent out from a noreply address but once this has been setup in one project/campaign, it appears you cannot set it up anywhere else.

**Comment by lukaprincic** [comment]
I'm stumbling over this too. It would be quite beneficial to have a sender that is shared across multiple projects.

**Comment by wmnnd** [comment]
Hey there, there are currently no shared SMTP senders in Keila. I originally added shared senders to Keila to support our the "Send with Keila" feature in our managed version. If you’re using a self-hosted instance of Keila, I’d recommend simply creating a new sender for each project.

@lukaprincic Sharing a sender across multiple projects in your account would be yet another feature. The shared senders refers to senders that are available to all users on a Keila instance (such as "Send with Keila" on keila.io).

I’ll close this issue for now because it’s not on our roadmap, but feel free if you’d like to take a stab at building it yourself and create a PR or to reach out if you’d like to sponsor this particular feature.

**Comment by flinthamm** [comment]
Hi @wmnnd and thank you for this update and your comments to help understand the situation. The only issue (at least with a self hosted instance) is that Keila won't allow you to use the same sender details i.e. a no-reply@ sender, which will be the same for different projects - although this will create lots of duplication, would it be easy to at least allow the same sender, I assume the email is used as a primary key or something?

I suspect I may have just misunderstood the way Keila is supposed to work, in which case I apologise and will have to re-visit , if there is an alternative. Thanks again.

**Comment by wmnnd** [comment]
@flinthamm The sender email indeed has a unique index. This is a precaution to make sure there aren’t every any mixups between different users. Eventually, I plan to loosen this restriction and overhaul the structure of senders (e.g. associate them with an account instead of with a project) - but there’s no timeline for this yet.

In the meantime, my recommendation would be to just use different addresses for different senders (or consider whether you actually want to use separate projects instead of segments when sending from the same address).

**Comment by wmnnd** [comment]
@flinthamm Actually, I thought about it some more … and adding shared SMTP senders would be pretty easy without changing anything about the current structure. The only thing is that you’d still have to define a unique From Address for every instance at the project level, but that email would be ignored. So you could just put something liken noreply+my-project@example.com but your emails would be sent from the From address defined globally in your shared sender.

Would that be helpful to your use-case?
