### ISSUE TITLE
Performance utilization should be improved

### ISSUE THREAD

**Issue by dompie** [pentacent/keila#318]
We are sending only to ~36k recipients out of ~450k with a rate of about 180/minute - but the produced load seems to be totally over the top. The machine we are sending from is a (almost) dedicated 4 core server with 16gb ram in our own infrastructure. No cloud stuff and no shared hosting.

![load-top](https://github.com/pentacent/keila/assets/706491/c546baa3-9e69-4b5c-9bde-e58d8b15be07)

If Keila really wants to becoma a succssful "Open Source alternative to newsletter tools like Mailchimp or Sendinblue" this must improve a lot.

**Comment by wmnnd** [comment]
Are you seeing this load while the recipients are being inserted or while the emails are actually going out?

**Comment by dompie** [comment]
This is the current progress:

![Screenshot 2024-07-09 at 14-04-30 Open Source Newsletter Tool · Keila](https://github.com/pentacent/keila/assets/706491/6170abe6-d436-463a-9190-26d46bd32625)

**Comment by wmnnd** [comment]
Well, the click rate and open rate has more to do with the content of your campaign and your email setup than with Keila.

Regarding the resource consumption: The more relevant number here is actually the pretty low memory consumption which tells me that your server is more than capable of handling this.
Elixir/Erlang applications aren’t usually CPU-constrained because they have their own scheduler and can make very efficient use of the existing resources.

In order to properly understand why your campaign is still using an unusual amount of CPU resources, I’d have to know more about how exactly your campaign was set up. I think you mentioned individualized links and using the block editor?

**Comment by dompie** [comment]
Yes, each email has about 9 personalized links and the campaign is a block campaign.

**Comment by wmnnd** [comment]
Keila 0.15.0 included a major rework of the email scheduler which should have massively increased performance when using rate-limited senders. I’m closing this issue now but I’d be happy to hear if the update was effective in your case as well 😊
