### ISSUE TITLE
Add strikeout text decoration as a markdown/rich text option.

### ISSUE THREAD

**Issue by AndyDufresne422** [pentacent/keila#319]
## First off, keila has been awesome! 
So thank you for making and maintaining this!

### Question:

Was wondering if I am just missing it or if it's possible to add stikeout?

### Possible solution:

If it doesn't exist in keila yet, a quick google search shows various implementations of strikeout in markdown, primarily the double tilde (as on github)
For example:
>```
>~~This is struck out~~
>```

Produces:
> ~~this is struck out~~

Could this possibly be implemented?

### Sometimes stirke out makes for ~~funny~~ cringy formatting.

**Comment by wmnnd** [comment]
Thank you for suggesting this! Strikeout is already supported in Markdown campaigns, just not through the Markdown rich text editor. That means, if you disable the rich text editor, you can type `~~struck out~~` and it will render correctly. Unfortunately that’s not yet supported in the rich text editor.

**Comment by AndyDufresne422** [comment]
Thanks for the quick response! And that's awesome to know!

Quick question... I started a campaign in block editor mode and have it 99% done. If I switch to the markdown editor, all of that will go away, right? And I would essentially start over?

Follow up question can I create columns in the markdown mode? Or is that a block editor feature only?

Thanks again for any help you can provide!

**Comment by wmnnd** [comment]
You can mostly switch between the Markdown WYSIWYG and plain Markdown editors without losing your campaign. There are some cases where things might break, and unfortunately using `~~` is one of them. If you add that in the plain Markdown editor and then switch back, it’s going to be escaped and work no longer.

But if you save your campaign first, you can simply give it a try! Switching from WYSWYG to plain Markdown for some final touch-ups shouldn’t break anything and you can make sure the email looks right by using the preview feature.

Columns are a block-editor-only feature only because there’s no good way to represent them with Markdown.
