### ISSUE TITLE
Segment editor should correctly parse segments with custom data fields

### ISSUE THREAD

**Issue by wmnnd** [pentacent/keila#92]
Currently, custom data fields can be added to a filter, but aren’t correctly converted back into form data after saving.

**Comment by panoramix360** [comment]
Hi @wmnnd, me and @gbottari were looking into this issue just to see what needs to be done.

We already know that we need to implement a new variation of the function `filter_condition_to_form_data` to type "custom".

But we noticed after looking into code, that this issue is already "In Progress" on your Roadmap, do you need any help?

Maybe we can give it a shot if you didn't start the implementation yet.

**Comment by wmnnd** [comment]
I’ve already fixed it in my local branch, I need to push it one of these days :joy:
